version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: patient-auto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "32769:5432"
    volumes:
      - patient-db:/var/lib/postgresql/data
  authentication-db:
    image: postgres
    environment:
      POSTGRES_DB: authentication-auto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "32768:5432"
    volumes:
      - authentication-db:/var/lib/postgresql/data
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

volumes:
  patient-db:
  authentication-db:
